### ISSUE TITLE
QFusion/Warsow crashes after multiple "vid_restart"s

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#138]
The steps to reproduce:
1) Start Warsow
2) Make vid_restart (any kind of it - via console or using bind)
3) Repeat step 2
...
N) Warsow gets crashed

Noticed facts:
- doesn't happen in Warsow 1.0
- wsw1.5/1.6/qf have it
- happens as on Windows 7 x64 as on Kubuntu 14.04 amd64
- on Win7 PC and on Win7 Laptop it usually happens near 39th vid_restart
- on Linux PC it usually happens near 80th vid_restart

Some screenshots of the crash on Win7:
![33](https://cloud.githubusercontent.com/assets/4707112/5676641/6753f898-97ea-11e4-9885-2abfee5297d2.png)
![36](https://cloud.githubusercontent.com/assets/4707112/5676640/67537d00-97ea-11e4-83cc-b31ce061d22a.png)
![38](https://cloud.githubusercontent.com/assets/4707112/5676643/6755d8ca-97ea-11e4-82f6-1279191198e7.png)
![39](https://cloud.githubusercontent.com/assets/4707112/5676642/6754e58c-97ea-11e4-9985-184bb911ba43.png)
The Error with "Failed to load default refresh DLL" is the most popular.

Some logs as from Win as from Lin:
win7 wsw1.6: http://pastebin.com/9FjnTMUt
lin wsw1.6: http://pastebin.com/Yise7Fv7
lin qf: http://pastebin.com/pAw4nThw (QFusion process has been frozen so i killed it by myself)

Typing vid_restart in cosole or pressing bind are too complicated, so I decied to automate this process:
1) Make autoexec.cfg with the following text http://pastebin.com/egqDpvDk
2) Drop into /basewsw and start the game
3) Autoexec will make ~110 vid_restarts and also create "console.txt" in the /basewsw
4) When crash will happen just open that console.txt and count "finished R_Init". Any advanced text-editor can count found text automatically.

**Comment by viciious** [comment]
Fixed in 06e5889485fd8a6d33d301718210080f836f562b

**Comment by adem4ik** [comment]
Ye, seems like this crash after 39/80 vid_restarts was fixed. But I've tried a lot more vid_restarts, and here are results:
1) Win7, crash after 169 vid_restarts, but now there is error window, just a message about a program being stopped to work like on 3d screen above.
2) Linux, crash after 334/333 vid_restarts. 

Process ends with "ERROR: Error opening pak file: ./basewsw/tex_36.pk3" on both OSes.

Logs: https://yadi.sk/d/y1fKLLiods8ya

Should I open a new issue?

**Comment by viciious** [comment]
Fixed in 9c31266d7c9e9a430de5b91a6306b253f12ac6e2

**Comment by adem4ik** [comment]
still gets crashed on 169/334 vid_restarts on Windows/Linux respectively.
Logs: https://yadi.sk/d/gfH2tOA8dsmoX

**Comment by viciious** [comment]
Can't reproduce this. I need your config.cfg

2015-01-10 13:38 GMT+03:00 Andrei Stepanov notifications@github.com:

> still gets crashed on 169/334 vid_restarts on Windows/Linux respectively.
> Logs: https://yadi.sk/d/gfH2tOA8dsmoX
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/138#issuecomment-69451448.

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
It was default config, clean installation w/o any external paks or configs except that autoexec.cfg, but here it is http://pastebin.com/C3WsSVVX

I can try to test it on laptop, but it would require much more time (since one vid_restart takes longer time there, about 10-15 secs, while on PC it is about 1-3 secs)

**Comment by adem4ik** [comment]
Ah, mb you have used old autoexec.cfg with only ~110 vid_restarts? I've used much more vid_restarts to reach that crash. Here is the new one with 500 vid_restarts: http://pastebin.com/PyyF4Gcf

**Comment by viciious** [comment]
Committed another fix in 39e60115968e8adfbb50a0a7880542b02620a260. This one should be final.

2015-01-10 18:51 GMT+03:00 Andrei Stepanov notifications@github.com:

> Ah, mb you have used old autoexec.cfg with only ~110 vid_restarts? I've
> used much more vid_restarts to reach that crash. Here is the new one with
> 500 vid_restarts: http://pastebin.com/PyyF4Gcf
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/138#issuecomment-69460278.

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
Crashes after 169/334 vid_restarts on Windows/Linux were fixed. But now there are crashes after 253/500 vid_restarts on Windows/Linux respectively.
![2015-01-11_191114](https://cloud.githubusercontent.com/assets/4707112/5695905/2fd5643a-99c8-11e4-96a6-966e85756c65.png)

Console outputs: https://yadi.sk/d/ABrgZCGcduAfn
A quick cut from Linux console output:

> ----- finished R_Init -----
> Successfully initialized XInput2 2.0
> ------- UI initialization -------
> LibRocket: Loaded font face Droid Sans Bold (from fonts/DroidSans-Bold.ttf).
> LibRocket: Loaded font face Droid Sans Regular (from fonts/DroidSans.ttf).
> LibRocket: Loaded font face Droid Sans Fallback Regular (from fonts/DroidSansFallback.ttf).
> LibRocket: Loaded font face Droid Sans Mono Regular (from fonts/DroidSansMono.ttf).
> LibRocket: Loaded font face warsow Regular (from fonts/ldrwswbeta.ttf).
> LibRocket: Loaded font face Silhouette Medium (from fonts/Silhouette.ttf).
> LibRocket: Loaded font face Virtue Regular (from fonts/Virtue.ttf).
> LibRocket: Loaded font face Hemi Head Bold Italic (from fonts/hemihead-bd-it.otf).
> LibRocket: Loaded font face Kimberley Black (from fonts/kimberley-bl.otf).
> LibRocket: WARNING: Unable to open file /ui/porkui/css/friends.rcss.
> LibRocket: ERROR: Failed to load style sheet /ui/porkui/css/friends.rcss.
> LibRocket: WARNING: Unable to open file /ui/porkui/as/base.as.
> ANGELSCRIPT: _script_0 7:2: Compiling void onFriendsLoad(Element@, Event@)
> ERROR: _script_0 22:3: No matching signatures to 'SetDocumentFontProperties(Element@&)'
> ANGELSCRIPT: _script_0 38:2: Compiling void friendsListTrackState()
> ERROR: _script_0 42:36: No matching signatures to 'GetUserLanguage()'
> WARNING: ScriptEventListener::fetchFunctionPtr failed with onFriendsLoad
> 
> ## ScriptEventListener: Not gonna call invalid function onFriendsLoad $onFriendsLoad
> 
> ---
> 
> ERROR: Error opening pak file: ./basewsw/tex_metal.pk3
> 
> ---
> 
> StreamCache::StreamDone: error -2 fetching 'http://www.warsow.net/blog/rml?lang=ru_ru'
> StreamCache::StreamDone: error -2 fetching 'http://www.warsow.net/blog/rml'
> Closing SDL audio device...
> SDL audio device shut down.
> Error: recursive error after: Error opening pak file: ./basewsw/tex_metal.pk3
> recursive error after: Error opening pak file: ./basewsw/tex_metal.pk3Cmd_RemoveCommand: in_restart not added
> _bla bla bla_
> Ошибка сегментирования

My guess, now it is leak somewhere inside LibRocket

Btw It is interesting that Linux needs 2x more vid_restarts than Windows before the crash, but somehow they both have it after the same amount of time, it took ~9 minutes in this case. Seems like vid_restart on Linux takes 2x less time than on Windows :b

**Comment by stopiccot** [comment]
Btw for me it looks like all this fixes are different kind of memory leaks. Maybe we should incorporate some static analysis\valgrind? They can be added as a buildstep on buildbot.

**Comment by viciious** [comment]
This is the same kind of leak in all commits. Besides, valgrid would have had a hard time detecting them since the engine keep holding references too the leaked file handles.

And on top of that, you'd need a proper OpenGL context to cover all those codepaths.

**Comment by viciious** [comment]
Btw, adem, your git checkout seems to be broken (again!). How could have /ui/porkui/as/base.as gone missing?

**Comment by adem4ik** [comment]
viciious, it was warsow who thought that some files were missing at last vid_restart before the crash, there are no such warnings before the crash. every file from the warnings is unbroken and existing on its own proper path.

**Comment by viciious** [comment]
Fixed in 8772da8e8b80d0f88ea3b03f6f06d4a286ee13de

**Comment by adem4ik** [comment]
So, i've spend 37 minutes on 1000 vid_restarts, even Win's 7 Aero has been crashed after 15 minutes, but not Warsow. Well done, Vic :b
