### ISSUE TITLE
Linear projectile bug

### ISSUE THREAD

**Issue by mikejsavage** [Qfusion/qfusion#424]
If you move into the trail of a rocket/plasma cell after it goes past it hits you, I believe it was introduced in this change:

https://github.com/Qfusion/qfusion/commit/82ce50b5a437020c8dba83c4e78ee2fa3a098e6b#diff-7355e72c777d4ae0a67c270273966264R890

Seems like it traces from the projectile start point to its current position every frame, rather than just tracing the distance covered

I think making that line

        VectorMA( ent->s.linearMovementBegin, flyTime - FRAMETIME, ent->s.linearMovementVelocity, start );

fixes it but it's late :)

**Comment by mikejsavage** [comment]
Loosely related, in G_RunFrame what's the different between `msec` and `serverTimeDelta`? It seems like they should be the same thing but if you print them they aren't always

edit: so `serverTimeDelta` is only used to step projectiles, and `FRAMETIME` comes from `msec`, so that fix is not quite right. I think `serverTimeDelta` should be nuked?

**Comment by viciious** [comment]
Yeah, the code needs to be changed to either store the previous position or the previous timestamp and trace from there to the current position.

> Loosely related, in G_RunFrame what's the different between msec and serverTimeDelta? It seems like they should be the same thing but if you print them they aren't always

To sustain the desired average framerate, the server may decide to run another extra game frame if enough delta time between previous frames has been accumulated. So `msec` is pretty much a fixed constant, `serverTimeDelta` is time delta for real clock. See `SV_RunGameFrame`

**Comment by viciious** [comment]
I am not sure whether it should be nuked or not since I didn't write this code in the first place.. From what I can remember, changing projectiles to advance in fixed ticks instead of real time clock is going to fuck them up

**Comment by mikejsavage** [comment]
Reading that code again `serverTimeDelta` only gets used when the game is paused, so it shouldn't matter

I think the proposed fix is correct

**Comment by viciious** [comment]
Wouldn't it push the projectile back a bit on the very first frame?

**Comment by mikejsavage** [comment]
you right

**Comment by mikejsavage** [comment]
or maybe it should trace from `ent->s.origin`?

        float endFlyTime = (float)( game.serverTime - ent->s.linearMovementTimeStamp ) * 0.001f;
        float startFlyTime = max( 0, endFlyTime - FRAMETIME );
        
        VectorMA( ent->s.linearMovementBegin, startFlyTime, ent->s.linearMovementVelocity, start );
        printf( "%f %f %f\n", start[ 0 ] - ent->s.origin[ 0 ], start[ 1 ] - ent->s.origin[ 1 ], start[ 2 ] - ent->s.origin[ 2 ] );

mostly prints 0s but occasionally deviates, e.g.

    0.000000 0.000000 0.000000
    0.000000 0.000000 0.000000
    0.000000 0.000000 0.000000
    0.000000 0.000000 0.000000
    4.979614 -0.411011 -0.184021
    -4.979736 0.411011 0.184021
    0.000000 0.000000 0.000000
    0.000000 0.000000 0.000000
    0.000000 0.000000 0.000000
    0.000000 0.000000 0.000000

5 units is pretty significant!

**Comment by viciious** [comment]
> mostly prints 0s but occasionally deviates, e.g.

That's weird. I've opted for another fix anyway :P
Fixed in f9caa65

**Comment by mikejsavage** [comment]
Rockets still go through the floor. My fix didn't work so I copied yours, and it still happens. Happens on qfusion master too:

https://streamable.com/i1afa

PG is unaffected for some reason

**Comment by viciious** [comment]
Can't reproduce it..

**Comment by viciious** [comment]
Perhaps it might have something to do with the code at the bottom of p_weapon.cpp

**Comment by mikejsavage** [comment]
![image](https://user-images.githubusercontent.com/579299/48921790-d3333680-eeaa-11e8-8180-725722cefa98.png)

http://f.mikejsavage.co.uk/backyard.bsp

**Comment by mikejsavage** [comment]
I undefined NO_ROCKET_ANTILAG and it seems to be better, will roll a release on our end and see how it is for everyone else

What's this PLASMAHACK in the same file btw? Looks like it gives volume to PG cells

**Comment by viciious** [comment]
I have no idea :D
Having SVN history would help but it's long gone.. My best guess is that it's got something to do with plasmaclimbing

**Comment by viciious** [comment]
So, has removing the NO_ROCKET_ANTILAG hack fixed the issue after all?

**Comment by mikejsavage** [comment]
one guy was complaining about disappearing rockets but it does seem better. will reopen if there's still a real issue here

edit: they watched the server demo and rockets were fine there. so it's something else

**Comment by viciious** [comment]
My guess is that G_ProjectileTimePrestep nudged the projectile's timestamp forwards in time which in turn caused the rockets to spawn further ahead but it failed to trace from ->s.origin to see if that movement was actually possible.

**Comment by viciious** [comment]
The whole prestep thing is a kind of black magic that has no scientific ground and was confirmed to "work" by subjective testing and to which everyone seems to have adapted to..
